//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportDetail.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> transport_date { get; set; }
        public Nullable<int> transport_company_id { get; set; }
        public Nullable<int> shipper_company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual company company1 { get; set; }
    }
}
